# Generated by Django 3.1.3 on 2021-04-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210423_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cnic',
            field=models.IntegerField(null=True),
        ),
    ]
