# Generated by Django 3.1.3 on 2021-04-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_profile_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
