# Generated by Django 3.1.3 on 2021-04-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20210424_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Picture',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
