# Generated by Django 3.1.3 on 2021-04-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20210424_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile1',
            name='cnic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile1',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
