# Generated by Django 3.1.3 on 2021-04-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20210424_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile1',
            name='Picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
