# Generated by Django 3.1.3 on 2021-04-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20210425_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile1',
            name='Picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
