# Generated by Django 3.1.3 on 2021-04-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20210425_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile1',
            old_name='Picture',
            new_name='picture',
        ),
    ]
