# Generated by Django 3.1.3 on 2021-04-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20210425_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile1',
            name='picture',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
