# Generated by Django 3.2 on 2021-04-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20210426_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile1',
            name='picture',
            field=models.ImageField(null=True, upload_to='media/images/uploads/'),
        ),
    ]
