# Generated by Django 3.1.3 on 2021-04-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_alter_profile1_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile1',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
