# Generated by Django 3.1.3 on 2021-04-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=32, null=True)),
                ('Destination', models.CharField(max_length=32, null=True)),
                ('picture', models.ImageField(upload_to='uploads/')),
                ('Sdate', models.DateField()),
                ('Edate', models.DateField()),
                ('About_Trip', models.CharField(max_length=100, null=True)),
                ('Included', models.CharField(max_length=100, null=True)),
                ('NotIncluded', models.CharField(max_length=100, null=True)),
                ('time', models.CharField(max_length=32, null=True)),
                ('city', models.CharField(max_length=32, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('itinerary', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('DeadLine', models.DateField()),
                ('discount', models.IntegerField()),
                ('Gsize', models.IntegerField()),
                ('Amount', models.IntegerField()),
            ],
        ),
    ]
