# Generated by Django 3.1.3 on 2021-04-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0003_trip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='people',
            field=models.IntegerField(null=True),
        ),
    ]
