# Generated by Django 3.1.3 on 2021-04-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0008_auto_20210424_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
