# Generated by Django 3.1.3 on 2021-04-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0009_auto_20210424_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='day',
            field=models.IntegerField(null=True),
        ),
    ]
