# Generated by Django 3.1.3 on 2021-04-25 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0010_trip_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='day',
        ),
    ]
