# Generated by Django 3.2 on 2021-04-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0011_remove_trip_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='picture',
            field=models.ImageField(upload_to='media/images/uploads/'),
        ),
    ]
