# Generated by Django 3.1.3 on 2021-04-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0012_alter_trip_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
