# Generated by Django 3.1.3 on 2021-04-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0013_auto_20210426_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
