# Generated by Django 3.2 on 2025-02-02 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0015_auto_20250201_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='Gsize',
        ),
    ]
