# Generated by Django 3.2 on 2025-02-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0016_remove_trip_gsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='Gsize',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
